trigger:
- main

pool:
  name: Linux-AP
  demands:
  - Agent.Name -equals demopool-vm

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet --info
  displayName: 'Verify .NET SDK Version'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: echo "Build completed successfully!"
  displayName: 'Completion Message'