trigger:
- main

pool:
  name: Linux-AP
  demands:
  - Agent.Name -equals demopool-vm

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet --info
  displayName: 'Verify .NET Installation'

- script: |
    # Build only the .NET Core projects explicitly
    dotnet build WebApp/WebApp.csproj --configuration $(buildConfiguration)
    dotnet build WebApp.UnitTest/WebApp.UnitTest.csproj --configuration $(buildConfiguration)
  displayName: 'Build .NET Core Projects Only'