trigger:
- main

pool:
  name: Linux-AP
  # demands:  # Commented out for testing

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
